server:
  port: 8101

spring:
  application:
    name: INVENTORY-SERVICE

  datasource:
    # url: jdbc:mysql://localhost:3306/inventory
    url: jdbc:mysql://mysql2:3306/inventory
    # url: jdbc:mysql://172.18.0.2:3306/inventory
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
