server:
  port: 8000

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: inventory-service
          # uri: http://localhost:8101
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**

        - id: shipping-service
          # uri: http://localhost:8100
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/api/shipping/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

